server:
  port: ${PORT:8081}

spring:
  application:
    name: user-service
  profiles:
    active: dev
  security:
    user:
      name: none
      password: none
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:}

  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      fail-fast: ${SPRING_CLOUD_CONFIG_FAIL_FAST:false}
      retry:
        initial-interval: 1000
        max-attempts: 6
        multiplier: 1.2
      # Nếu cần chỉ rõ label/branch trong config repo
      label: ${SPRING_CLOUD_CONFIG_LABEL:main}

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE