# application-prod.yml
server:
  port: ${PORT:8081}

spring:
  application:
    name: user-service

  # Sử dụng Config Server public URL, optional để service không fail nếu không reach được
  config:
    import: optional:configserver:https://config-server-production-9a61.up.railway.app/

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: https://phenikaa-thesis-management-production.up.railway.app/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${RAILWAY_STATIC_URL:phenikaa-thesis-management-production.up.railway.app}
    non-secure-port: ${PORT:8081}
    secure-port-enabled: false
    prefer-ip-address: false

jwt:
  secret: ${JWT_SECRET:VHJlbmRvaW5heW5ndW9pZGFuZ2RldHJhbnRyb25nbmFodGFsYW5ndW9pZGFzYW5zYW5nYm90aG9pZ2lhbmRlY2hhbXNvY2JhblRob2lnaWFuY3VhYWljdW5nZGV1ZGFuZ3F1eW5odW5oYWVkZW10aG9pZ2lhbmN1YW5ndW95ZGFuaGNob2JhbmNvbmdnaW9uZ2h1dmllY2RlbWNhdGhlZ2lvaWN1YWJhbnRoYW5jaGlhc2VjdW5nYmFu}
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.security: INFO
