#server:
#  port: 8081
#
#spring:
#  application:
#    name: user-service
#  profiles:
#    active: dev
#  config:
#    import: "configserver:"
#
#  cloud:
#    config:
#      uri: http://localhost:8888
#      fail-fast: true
#      retry:
#        initial-interval: 1000
#        max-attempts: 6
#        multiplier: 1.2
#
#logging:
#  level:
#    org.springframework: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: ${PORT:8081}

spring:
  application:
    name: user-service
  profiles:
    active: dev

  # Ưu tiên cấu hình qua ENV; khi local không set ENV sẽ fallback localhost
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:}

  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      # Có thể bật/tắt fail-fast qua ENV, default false để không crash khi config server chưa sẵn sàng
      fail-fast: ${SPRING_CLOUD_CONFIG_FAIL_FAST:false}
      retry:
        initial-interval: 1000
        max-attempts: 6
        multiplier: 1.2
      # Nếu cần chỉ rõ label/branch trong config repo
      label: ${SPRING_CLOUD_CONFIG_LABEL:main}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE