[build]
builder = "nixpacks"

[build.environment]
JAVA_VERSION = "21"

# Discovery Server
[[services]]
name = "discovery-server"
source = "discovery/discovery-server"
[services.build]
command = "mvn -DskipTests package"
[services.deploy]
startCommand = "java -Dserver.port=$PORT -jar target/discovery-server-*.jar"

# Config Server
[[services]]
name = "config-server"
source = "config/config-server"
[services.build]
command = "mvn -DskipTests package"
[services.deploy]
startCommand = "java -Dserver.port=$PORT -jar target/config-server-*.jar"

# API Gateway
[[services]]
name = "api-gateway"
source = "gateway/api-gateway"
[services.build]
command = "mvn -DskipTests package"
[services.deploy]
startCommand = "java -Dserver.port=$PORT -jar target/api-gateway-*.jar"

# User Service
[[services]]
name = "user-service"
source = "services/user-service"
[services.build]
command = "mvn -DskipTests package"
[services.deploy]
startCommand = "java -Dserver.port=$PORT -jar target/user-service-*.jar"

# Thesis Service
[[services]]
name = "thesis-service"
source = "services/thesis-service"
[services.build]
command = "mvn -DskipTests package"
[services.deploy]
startCommand = "java -Dserver.port=$PORT -jar target/thesis-service-*.jar"

# Submission Service
[[services]]
name = "submission-service"
source = "services/submission-service"
[services.build]
command = "mvn -DskipTests package"
[services.deploy]
startCommand = "java -Dserver.port=$PORT -jar target/submission-service-*.jar"

# Communication Log Service
[[services]]
name = "communication-log-service"
source = "services/communication-log-service"
[services.build]
command = "mvn -DskipTests package"
[services.deploy]
startCommand = "java -Dserver.port=$PORT -jar target/communication-log-service-*.jar"

# Eval Service
[[services]]
name = "eval-service"
source = "services/eval-service"
[services.build]
command = "mvn -DskipTests package"
[services.deploy]
startCommand = "java -Dserver.port=$PORT -jar target/eval-service-*.jar"

# Assign Service
[[services]]
name = "assign-service"
source = "services/assign-service"
[services.build]
command = "mvn -DskipTests package"
[services.deploy]
startCommand = "java -Dserver.port=$PORT -jar target/assign-service-*.jar"

# Academic Config Service
[[services]]
name = "academic-config-service"
source = "services/academic-config-service"
[services.build]
command = "mvn -DskipTests package"
[services.deploy]
startCommand = "java -Dserver.port=$PORT -jar target/academic-config-service-*.jar"
