[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar discovery/discovery-server/target/discovery-server-1.0-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables for discovery server
[env]
SPRING_PROFILES_ACTIVE = "prod"
PORT = "8761"
