[build]
builder = "dockerfile"

[deploy]
startCommand = "java -jar discovery-server.jar"

# Discovery Server
[[services]]
name = "discovery-server"
source = "."
[services.deploy]
startCommand = "java -jar discovery-server.jar"

# Config Server  
[[services]]
name = "config-server"
source = "."
[services.deploy]
startCommand = "java -jar config-server.jar"

# API Gateway
[[services]]
name = "api-gateway"
source = "."
[services.deploy]
startCommand = "java -jar api-gateway.jar"

# User Service
[[services]]
name = "user-service"
source = "."
[services.deploy]
startCommand = "java -jar user-service.jar"

# Thesis Service
[[services]]
name = "thesis-service"
source = "."
[services.deploy]
startCommand = "java -jar thesis-service.jar"

# Submission Service
[[services]]
name = "submission-service"
source = "."
[services.deploy]
startCommand = "java -jar submission-service.jar"

# Communication Log Service
[[services]]
name = "communication-log-service"
source = "."
[services.deploy]
startCommand = "java -jar communication-log-service.jar"

# Eval Service
[[services]]
name = "eval-service"
source = "."
[services.deploy]
startCommand = "java -jar eval-service.jar"

# Assign Service
[[services]]
name = "assign-service"
source = "."
[services.deploy]
startCommand = "java -jar assign-service.jar"

# Academic Config Service
[[services]]
name = "academic-config-service"
source = "."
[services.deploy]
startCommand = "java -jar academic-config-service.jar"
