server:
  port: ${PORT:8888}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hieudoanthe/phenikaa-config-repo.git
          default-label: main
          search-paths:
            - thesis-service
            - user-service
            - academic-config-service
            - assign-service
            - communication-log-service
            - eval-service
            - group-service
            - profile-service
            - submission-service
            - auth-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.cloud.config: INFO
