server:
  port: 8090

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  security:
    user:
      name: none
      password: none
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6
        multiplier: 1.2

debug: true
logging:
  level:
    org.springframework.security: DEBUG
