server:
  port: 8084

spring:
  application:
    name: eval-service
  profiles:
    active: dev
  config:
    import: "configserver:"

# Logging
logging:
  level:
    com.phenikaa.evalservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
