server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  security:
    user:
      name: none
      password: none
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/student/**, /api/admin/**, /api/teacher/**, /api/auth/**, /internal/users/**

        - id: thesis-service
          uri: lb://thesis-service
          predicates:
            - Path=/api/lecturer/thesis/**, /api/thesis-service/teacher/**, /api/thesis-service/student/**, /api/thesis-service/admin/**

        - id: assign-service
          uri: lb://assign-service
          predicates:
            - Path=/api/assign-service/**

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profile-service/**

        - id: academic-config-service
          uri: lb://academic-config-service
          predicates:
            - Path=/api/academic-config-service/**

        - id: communication-log-service
          uri: lb://communication-log-service
          predicates:
            - Path=/notifications/**, /chat/**

        - id: communication-log-service-ws
          uri: lb:ws://communication-log-service
          predicates:
            - Path=/ws/notifications/**, /ws/chat/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: VHJlbmRvaW5heW5ndW9pZGFuZ2RldHJhbnRyb25nbmFodGFsYW5ndW9pZGFzYW5zYW5nYm90aG9pZ2lhbmRlY2hhbXNvY2JhblRob2lnaWFuY3VhYWljdW5nZGV1ZGFuZ3F1eW5odW5oYWVkZW10aG9pZ2lhbmN1YW5ndW95ZGFuaGNob2JhbmNvbmdnaW9uZ2h1dmllY2RlbWNhdGhlZ2lvaWN1YWJhbnRoYW5jaGlhc2VjdW5nYmFu
  expiration: 86400000 # 1 ngày (tính bằng milliseconds)
  refresh-expiration: 604800000

debug: true
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.web.filter.CorsFilter: DEBUG
