server:
  port: ${PORT:8080}

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/student/**, /api/admin/**, /api/teacher/**, /api/auth/**, /internal/users/**
        - id: thesis-service
          uri: lb://thesis-service
          predicates:
            - Path=/api/thesis-service/teacher/**, /api/thesis-service/student/**, /api/thesis-service/admin/**, /api/thesis-service/student-period/**, /api/thesis-service/ai-chat/**
        - id: assign-service
          uri: lb://assign-service
          predicates:
            - Path=/api/assign-service/**
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profile-service/**
        - id: academic-config-service
          uri: lb://academic-config-service
          predicates:
            - Path=/api/academic-config-service/**
        - id: eval-service
          uri: lb://eval-service
          predicates:
            - Path=/api/eval-service/admin/**, /api/eval-service/teacher/**, /api/eval-service/student/**
        - id: submission-service
          uri: lb://submission-service
          predicates:
            - Path=/api/submission-service/**
        - id: communication-log-service
          uri: lb://communication-log-service
          predicates:
            - Path=/notifications/**, /chat/**, /api/communication-log-service/**
        - id: communication-log-service-ws
          uri: lb:ws://communication-log-service
          predicates:
            - Path=/ws/notifications/**, /ws/chat/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${RAILWAY_STATIC_URL:}}
    non-secure-port: ${EUREKA_INSTANCE_NONSECUREPORT:80}
    secure-port-enabled: ${EUREKA_INSTANCE_SECUREPORT_ENABLED:true}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}

jwt:
  secret: ${JWT_SECRET:VHJlbmRvaW5heW5ndW9pZGFuZ2RldHJhbnRyb25nbmFodGFsYW5ndW9pZGFzYW5zYW5nYm90aG9pZ2lhbmRlY2hhbXNvY2JhblRob2lnaWFuY3VhYWljdW5nZGV1ZGFuZ3F1eW5odW5oYWVkZW10aG9pZ2lhbmN1YW5ndW95ZGFuaGNob2JhbmNvbmdnaW9uZ2h1dmllY2RlbWNhdGhlZ2lvaWN1YWJhbnRoYW5jaGlhc2VjdW5nYmFu}
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web.cors: INFO
    org.springframework.web.socket: INFO
