server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  security:
    user:
      name: none
      password: none
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:lb://auth-service}
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: ${USER_SERVICE_URL:lb://user-service}
          predicates:
            - Path=/api/user-service/student/**, /api/admin/**, /api/teacher/**, /internal/users/**

        - id: thesis-service
          uri: ${THESIS_SERVICE_URL:lb://thesis-service}
          predicates:
            - Path=/api/thesis-service/teacher/**, /api/thesis-service/student/**, /api/thesis-service/admin/**, /api/thesis-service/student-period/**, /api/thesis-service/ai-chat/**, /internal/thesis/**

        - id: assign-service
          uri: ${ASSIGN_SERVICE_URL:lb://assign-service}
          predicates:
            - Path=/api/assign-service/**, /internal/assignments/**

        - id: profile-service
          uri: ${PROFILE_SERVICE_URL:lb://profile-service}
          predicates:
            - Path=/api/profile-service/**, /internal/profiles/**

        - id: academic-config-service
          uri: ${ACADEMIC_CONFIG_SERVICE_URL:lb://academic-config-service}
          predicates:
            - Path=/api/academic-config-service/**, /internal/academic/**

        - id: eval-service
          uri: ${EVAL_SERVICE_URL:lb://eval-service}
          predicates:
            - Path=/api/eval-service/admin/**, /api/eval-service/teacher/**, /api/eval-service/student/**, /internal/evaluations/**

        - id: submission-service
          uri: ${SUBMISSION_SERVICE_URL:lb://submission-service}
          predicates:
            - Path=/api/submission-service/**, /internal/submissions/**

        - id: communication-log-service
          uri: ${COMM_LOG_SERVICE_URL:lb://communication-log-service}
          predicates:
            - Path=/notifications/**, /chat/**, /api/communication-log-service/**

        - id: communication-log-service-ws
          uri: ${COMM_LOG_SERVICE_WS_URL:lb:ws://communication-log-service}
          predicates:
            - Path=/ws/notifications/**, /ws/chat/**

        - id: statistics-service
          uri: ${STATISTICS_SERVICE_URL:lb://statistics-service}
          predicates:
            - Path=/api/statistics-service/**

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${RAILWAY_PUBLIC_DOMAIN:api-gateway-production-95a5.up.railway.app} # hostname public
    instance-id: ${spring.application.name}:${random.value}
    non-secure-port: 8080
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: VHJlbmRvaW5heW5ndW9pZGFuZ2RldHJhbnRyb25nbmFodGFsYW5ndW9pZGFzYW5zYW5nYm90aG9pZ2lhbmRlY2hhbXNvY2JhblRob2lnaWFuY3VhYWljdW5nZGV1ZGFuZ3F1eW5odW5oYWVkZW10aG9pZ2lhbmN1YW5ndW95ZGFuaGNob2JhbmNvbmdnaW9uZ2h1dmllY2RlbWNhdGhlZ2lvaWN1YWJhbnRoYW5jaGlhc2VjdW5nYmFu
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    org.springframework.security: WARN
    org.springframework.web.socket: DEBUG
