server:
  port: 8091

spring:
  application:
    name: statistics-service
  profiles:
    active: dev
  security:
    user:
      name: none
      password: none
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:}

  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      fail-fast: ${SPRING_CLOUD_CONFIG_FAIL_FAST:false}
      retry:
        initial-interval: 1000
        max-attempts: 6
        multiplier: 1.2
      label: ${SPRING_CLOUD_CONFIG_LABEL:main}

logging:
  level:
    com.phenikaa.statisticsservice: DEBUG
